---
- hosts: all
  become: true
  vars: 
    install: true

  roles:
    - { role: install_containerd, when: ansible_os_family == 'Debian' }
    - { role: disable_swap, when: ansible_os_family == 'Debian' }
    - { role: install_kubeadm, when: ansible_os_family == 'Debian' }
    - { role: initialise_cluster, when: ansible_os_family == 'Debian' }
    - { role: install_kube_network, when: ansible_os_family == 'Debian' }

# - hosts: master-1
#  become: true
#  roles:
#    - { role: initialise_cluster, when: ansible_os_family == 'Debian' }

#   handlers:
#     - name: Enable httpd
#       service: name=httpd state=started
#       listen: "start_enable_httpd"
#     - name: Allow http and https firewall access
#       firewalld:
#         service: '{{ item }}'
#         state: enabled
#         permanent: True
#         immediate: True
#         with_items:
#         - http
#         - https
#         listen: add_http_https_firewall
